import type { Body, Format, Tier } from './catalog'

export interface ReferenceLens {
  name: string
  focal: number
  fNumber: number
  format: Format
  body: Body
  tier: Tier
  diameter: number
  length: number
  weight: number
  filter: number | null
  elements: number
}

/** Published figures, rounded. Used for the "nearest production lens" hint. */
export const referenceLenses: ReferenceLens[] = [
  {
    name: 'Sony FE 50mm F1.8',
    focal: 50,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 68.6,
    length: 59.5,
    weight: 186,
    filter: 49,
    elements: 6,
  },
  {
    name: 'Sony FE 50mm F1.2 GM',
    focal: 50,
    fNumber: 1.2,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 87,
    length: 108,
    weight: 778,
    filter: 72,
    elements: 14,
  },
  {
    name: 'Sigma 50mm F1.4 DG DN Art',
    focal: 50,
    fNumber: 1.4,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 78.2,
    length: 109.5,
    weight: 670,
    filter: 72,
    elements: 14,
  },
  {
    name: 'Sony FE 85mm F1.8',
    focal: 85,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 78,
    length: 82,
    weight: 371,
    filter: 67,
    elements: 9,
  },
  {
    name: 'Sony FE 85mm F1.4 GM',
    focal: 85,
    fNumber: 1.4,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 89.5,
    length: 107.5,
    weight: 820,
    filter: 77,
    elements: 11,
  },
  {
    name: 'Sony FE 135mm F1.8 GM',
    focal: 135,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 89.5,
    length: 127,
    weight: 950,
    filter: 82,
    elements: 13,
  },
  {
    name: 'Sony FE 24mm F1.4 GM',
    focal: 24,
    fNumber: 1.4,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 75.4,
    length: 92.4,
    weight: 445,
    filter: 67,
    elements: 13,
  },
  {
    name: 'Sony FE 24mm F2.8 G',
    focal: 24,
    fNumber: 2.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 68,
    length: 45,
    weight: 162,
    filter: 49,
    elements: 8,
  },
  {
    name: 'Sony FE 35mm F1.8',
    focal: 35,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 65.6,
    length: 73,
    weight: 280,
    filter: 55,
    elements: 11,
  },
  {
    name: 'Sony FE 20mm F1.8 G',
    focal: 20,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 73.5,
    length: 84.7,
    weight: 373,
    filter: 67,
    elements: 14,
  },
  {
    name: 'Sony FE 14mm F1.8 GM',
    focal: 14,
    fNumber: 1.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 83,
    length: 99.8,
    weight: 460,
    filter: null,
    elements: 14,
  },
  {
    name: 'Sony FE 300mm F2.8 GM',
    focal: 300,
    fNumber: 2.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 124,
    length: 265,
    weight: 1470,
    filter: null,
    elements: 21,
  },
  {
    name: 'Sony FE 400mm F2.8 GM',
    focal: 400,
    fNumber: 2.8,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 158,
    length: 359,
    weight: 2895,
    filter: null,
    elements: 23,
  },
  {
    name: 'Sony FE 600mm F4 GM',
    focal: 600,
    fNumber: 4,
    format: 'ff',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 163.6,
    length: 449,
    weight: 3040,
    filter: null,
    elements: 24,
  },
  {
    name: 'Nikon Z 40mm f/2',
    focal: 40,
    fNumber: 2,
    format: 'ff',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 70,
    length: 45.5,
    weight: 170,
    filter: 52,
    elements: 6,
  },
  {
    name: 'Canon EF 50mm f/1.8 STM',
    focal: 50,
    fNumber: 1.8,
    format: 'ff',
    body: 'slr',
    tier: 'classic',
    diameter: 69.2,
    length: 39.3,
    weight: 160,
    filter: 49,
    elements: 6,
  },
  {
    name: 'Canon EF 85mm f/1.2L II',
    focal: 85,
    fNumber: 1.2,
    format: 'ff',
    body: 'slr',
    tier: 'classic',
    diameter: 91.5,
    length: 84,
    weight: 1025,
    filter: 72,
    elements: 8,
  },
  {
    name: 'Nikon AF-S 85mm f/1.8G',
    focal: 85,
    fNumber: 1.8,
    format: 'ff',
    body: 'slr',
    tier: 'modern',
    diameter: 80,
    length: 73,
    weight: 350,
    filter: 67,
    elements: 9,
  },
  {
    name: 'Canon EF 300mm f/2.8L IS II',
    focal: 300,
    fNumber: 2.8,
    format: 'ff',
    body: 'slr',
    tier: 'modern',
    diameter: 128,
    length: 248,
    weight: 2350,
    filter: null,
    elements: 16,
  },
  {
    name: 'Fujifilm XF 35mm F1.4 R',
    focal: 35,
    fNumber: 1.4,
    format: 'apsc',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 65,
    length: 54.9,
    weight: 187,
    filter: 52,
    elements: 8,
  },
  {
    name: 'Fujifilm XF 56mm F1.2 R WR',
    focal: 56,
    fNumber: 1.2,
    format: 'apsc',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 79.4,
    length: 76,
    weight: 445,
    filter: 67,
    elements: 13,
  },
  {
    name: 'Fujifilm XF 23mm F2 R WR',
    focal: 23,
    fNumber: 2,
    format: 'apsc',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 60,
    length: 51.9,
    weight: 180,
    filter: 43,
    elements: 10,
  },
  {
    name: 'Olympus M.Zuiko 45mm F1.8',
    focal: 45,
    fNumber: 1.8,
    format: 'mft',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 56,
    length: 46,
    weight: 116,
    filter: 37,
    elements: 9,
  },
  {
    name: 'Olympus M.Zuiko 25mm F1.8',
    focal: 25,
    fNumber: 1.8,
    format: 'mft',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 57.8,
    length: 42,
    weight: 137,
    filter: 46,
    elements: 9,
  },
  {
    name: 'Olympus M.Zuiko 75mm F1.8',
    focal: 75,
    fNumber: 1.8,
    format: 'mft',
    body: 'mirrorless',
    tier: 'modern',
    diameter: 64,
    length: 69,
    weight: 305,
    filter: 58,
    elements: 10,
  },
  {
    name: 'Panasonic Leica DG 12mm F1.4',
    focal: 12,
    fNumber: 1.4,
    format: 'mft',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 70,
    length: 70,
    weight: 335,
    filter: 62,
    elements: 15,
  },
  {
    name: 'Fujinon GF 110mm F2 R LM WR',
    focal: 110,
    fNumber: 2,
    format: 'mf',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 94.3,
    length: 125.5,
    weight: 1010,
    filter: 77,
    elements: 14,
  },
  {
    name: 'Fujinon GF 63mm F2.8 R WR',
    focal: 63,
    fNumber: 2.8,
    format: 'mf',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 84,
    length: 71,
    weight: 405,
    filter: 62,
    elements: 10,
  },
  {
    name: 'Fujinon GF 23mm F4 R LM WR',
    focal: 23,
    fNumber: 4,
    format: 'mf',
    body: 'mirrorless',
    tier: 'flagship',
    diameter: 89.8,
    length: 103,
    weight: 845,
    filter: 82,
    elements: 15,
  },
]
