import { computed } from '@reatom/core'

import { resolvedThemeMode, themePack } from './model'
import type { ResolvedThemeMode, ThemePack } from './types'

export type ThemeVariables = Record<`--${string}`, string>

type ThemeDefinition = Record<ResolvedThemeMode, ThemeVariables>
type ThemeMeta = {
  value: ThemePack
  label: string
  description: string
  swatches: readonly [string, string, string]
}

export const THEME_PACKS: ThemeMeta[] = [
  {
    value: 'blueprint',
    label: 'Blueprint',
    description: 'Architectural sheets, cobalt ink, measured details',
    swatches: ['#234fa0', '#dbe7fa', '#f4f3ec'],
  },
  {
    value: 'terminal',
    label: 'Terminal',
    description: 'Monospace TUI, scanlines, hard edges',
    swatches: ['#7cff6b', '#0b120b', '#f4f6ef'],
  },
  {
    value: 'paper',
    label: 'Paper',
    description: 'Warm whites, clean lines, blue and blush details',
    swatches: ['#526f86', '#e8b4bc', '#f7f7f2'],
  },
  {
    value: 'polaroid',
    label: 'Polaroid',
    description: 'Photo prints, desk shadows, tape labels',
    swatches: ['#d94f45', '#f6ead2', '#5f7ea3'],
  },
  {
    value: 'obsidian',
    label: 'Obsidian',
    description: 'Volcanic glass, Gothic arches and silver light',
    swatches: ['#0b0c10', '#51435f', '#c6bfd8'],
  },
  {
    value: 'bauhaus',
    label: 'Bauhaus',
    description: 'Primary blocks, bold flat geometry',
    swatches: ['#c63c2b', '#e8bb35', '#254bbc'],
  },
  {
    value: 'glass',
    label: 'Glass',
    description: 'Clear lenses, silver light, optical depth',
    swatches: ['#ffffff', '#c7c7c7', '#333333'],
  },
  {
    value: 'minimal',
    label: 'Minimal',
    description: 'A photographic index. Space, type, and nothing extra.',
    swatches: ['#111111', '#777777', '#f7f7f7'],
  },
  {
    value: 'retroOs',
    label: 'Retro OS',
    description: 'Beveled windows, segmented controls',
    swatches: ['#2563eb', '#c7c7c7', '#3f3f46'],
  },
]

const transparentLayer = 'linear-gradient(transparent, transparent)'

const THEMES = {
  blueprint: {
    dark: {
      '--font-ui': '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
      '--bg-primary': '#234b91',
      '--bg-secondary': '#204587',
      '--bg-tertiary': '#305ba0',
      '--bg-elevated': '#254e94',
      '--surface-glass': '#234b91',
      '--surface-strong': 'var(--bg-secondary)',
      '--accent': '#ecf2ff',
      '--accent-hover': '#ffffff',
      '--accent-soft': '#ffffff15',
      '--accent-contrast': '#204587',
      '--text-primary': '#f2f5ff',
      '--text-secondary': '#d0def4',
      '--text-muted': '#b3c9ed',
      '--card-bg': 'var(--bg-primary)',
      '--card-border': '#b7d0fa70',
      '--border': '#b7d0fa45',
      '--border-strong': '#dce9ff99',
      '--toolbar-bg': 'var(--bg-secondary)',
      '--panel-bg': 'var(--bg-secondary)',
      '--input-bg': '#ffffff08',
      '--input-border': '#b7d0fa70',
      '--hover-bg': '#ffffff15',
      '--active-bg': '#ffffff1f',
      '--scrollbar-thumb': '#b7d0fa70',
      '--shadow': 'rgba(3, 14, 24, 0)',
      '--shadow-strong': 'rgba(3, 14, 24, 0)',
      '--focus-ring': '#ecf2ff',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(32, 69, 135, 0.78)',
      '--blueprint-viewer-surface': 'rgba(32, 69, 135, 0.76)',
      '--overlay-control': '#16386fdd',
      '--overlay-control-hover': '#285299',
      '--image-overlay': '#173467b0',
      '--app-bg-image':
        'linear-gradient(rgba(205,224,255,.045) 1px, transparent 1px), linear-gradient(90deg, rgba(205,224,255,.045) 1px, transparent 1px), linear-gradient(rgba(205,224,255,.09) 1px, transparent 1px), linear-gradient(90deg, rgba(205,224,255,.09) 1px, transparent 1px)',
      '--surface-bg-image':
        'none',
      '--card-bg-image': transparentLayer,
      '--bg-size': '24px 24px, 24px 24px, 120px 120px, 120px 120px',
      '--surface-bg-size': '24px 24px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '10px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px var(--accent)',
      '--selected-shadow': 'inset 0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
    light: {
      '--font-ui': '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
      '--bg-primary': '#f4f3ec',
      '--bg-secondary': '#eeeee7',
      '--bg-tertiary': '#e1e7ed',
      '--bg-elevated': '#fafaf5',
      '--surface-glass': '#f4f3ec',
      '--surface-strong': '#eeeee7',
      '--accent': '#234f9b',
      '--accent-hover': '#173d80',
      '--accent-soft': '#234f9b10',
      '--accent-contrast': '#fafaf5',
      '--text-primary': '#214985',
      '--text-secondary': '#365d94',
      '--text-muted': '#536e94',
      '--card-bg': '#f9f9f3',
      '--card-border': '#234f9b70',
      '--border': '#234f9b38',
      '--border-strong': '#234f9b99',
      '--toolbar-bg': 'var(--bg-secondary)',
      '--panel-bg': 'var(--bg-secondary)',
      '--input-bg': '#234f9b05',
      '--input-border': '#234f9b60',
      '--hover-bg': '#234f9b10',
      '--active-bg': '#234f9b18',
      '--scrollbar-thumb': '#234f9b60',
      '--shadow': 'rgba(6, 34, 53, 0)',
      '--shadow-strong': 'rgba(6, 34, 53, 0)',
      '--focus-ring': '#234f9b',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(244, 243, 236, 0.76)',
      '--blueprint-viewer-surface': 'rgba(238, 238, 231, 0.76)',
      '--overlay-control': '#173d80dd',
      '--overlay-control-hover': '#234f9b',
      '--image-overlay': 'rgba(3, 13, 24, 0.48)',
      '--app-bg-image':
        'linear-gradient(rgba(35,79,155,.045) 1px, transparent 1px), linear-gradient(90deg, rgba(35,79,155,.045) 1px, transparent 1px), linear-gradient(rgba(35,79,155,.09) 1px, transparent 1px), linear-gradient(90deg, rgba(35,79,155,.09) 1px, transparent 1px)',
      '--surface-bg-image':
        'none',
      '--card-bg-image': transparentLayer,
      '--bg-size': '24px 24px, 24px 24px, 120px 120px, 120px 120px',
      '--surface-bg-size': '24px 24px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '10px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px var(--accent)',
      '--selected-shadow': 'inset 0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
  },
  terminal: {
    dark: {
      '--font-ui': '"SFMono-Regular", "Cascadia Mono", Consolas, monospace',
      '--bg-primary': '#071007',
      '--bg-secondary': '#0b150b',
      '--bg-tertiary': '#102010',
      '--bg-elevated': '#101b10',
      '--surface-glass': 'rgba(7, 16, 7, 0.96)',
      '--surface-strong': 'rgba(11, 21, 11, 0.98)',
      '--accent': '#7cff6b',
      '--accent-hover': '#b7ff9f',
      '--accent-soft': 'rgba(124, 255, 107, 0.14)',
      '--accent-contrast': '#071007',
      '--text-primary': '#c9ffc2',
      '--text-secondary': '#8ddf85',
      '--text-muted': '#4e8f4e',
      '--card-bg': 'rgba(0, 0, 0, 0.28)',
      '--card-border': 'rgba(124, 255, 107, 0.32)',
      '--border': 'rgba(124, 255, 107, 0.28)',
      '--border-strong': 'rgba(124, 255, 107, 0.48)',
      '--toolbar-bg': 'rgba(5, 12, 5, 0.98)',
      '--panel-bg': 'rgba(6, 14, 6, 0.98)',
      '--input-bg': 'rgba(124, 255, 107, 0.055)',
      '--input-border': 'rgba(124, 255, 107, 0.34)',
      '--hover-bg': 'rgba(124, 255, 107, 0.1)',
      '--active-bg': 'rgba(124, 255, 107, 0.16)',
      '--scrollbar-thumb': 'rgba(124, 255, 107, 0.32)',
      '--shadow': 'rgba(0, 0, 0, 0)',
      '--shadow-strong': 'rgba(0, 0, 0, 0)',
      '--focus-ring': 'rgba(124, 255, 107, 0.3)',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'rgba(124, 255, 107, 0.16)',
      '--hero-glow-2': 'rgba(255, 176, 76, 0.08)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.94)',
      '--overlay-control': 'rgba(124, 255, 107, 0.12)',
      '--overlay-control-hover': 'rgba(124, 255, 107, 0.22)',
      '--image-overlay': 'rgba(0, 0, 0, 0.72)',
      '--app-bg-image':
        'linear-gradient(rgba(124,255,107,.05) 50%, rgba(0,0,0,.05) 50%)',
      '--surface-bg-image':
        'linear-gradient(rgba(124,255,107,.035) 50%, transparent 50%)',
      '--card-bg-image': transparentLayer,
      '--bg-size': '100% 4px',
      '--surface-bg-size': '100% 4px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px var(--accent)',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
    light: {
      '--font-ui': '"SFMono-Regular", "Cascadia Mono", Consolas, monospace',
      '--bg-primary': '#f4f6ef',
      '--bg-secondary': '#fbfcf7',
      '--bg-tertiary': '#e4eadf',
      '--bg-elevated': '#ffffff',
      '--surface-glass': 'rgba(251, 252, 247, 0.98)',
      '--surface-strong': 'rgba(255, 255, 255, 0.98)',
      '--accent': '#0f6b3a',
      '--accent-hover': '#064e2f',
      '--accent-soft': 'rgba(15, 107, 58, 0.11)',
      '--accent-contrast': '#f8fff5',
      '--text-primary': '#172018',
      '--text-secondary': '#34513a',
      '--text-muted': '#6b7a6d',
      '--card-bg': 'rgba(255, 255, 252, 0.82)',
      '--card-border': 'rgba(15, 107, 58, 0.3)',
      '--border': 'rgba(15, 107, 58, 0.24)',
      '--border-strong': 'rgba(15, 107, 58, 0.44)',
      '--toolbar-bg': 'rgba(248, 250, 243, 0.98)',
      '--panel-bg': 'rgba(248, 250, 243, 0.98)',
      '--input-bg': 'rgba(15, 107, 58, 0.055)',
      '--input-border': 'rgba(15, 107, 58, 0.3)',
      '--hover-bg': 'rgba(15, 107, 58, 0.085)',
      '--active-bg': 'rgba(15, 107, 58, 0.12)',
      '--scrollbar-thumb': 'rgba(15, 107, 58, 0.24)',
      '--shadow': 'rgba(23, 32, 24, 0)',
      '--shadow-strong': 'rgba(23, 32, 24, 0)',
      '--focus-ring': 'rgba(15, 107, 58, 0.22)',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'rgba(15, 107, 58, 0.08)',
      '--hero-glow-2': 'rgba(49, 81, 58, 0.06)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.9)',
      '--overlay-control': 'rgba(255, 249, 232, 0.16)',
      '--overlay-control-hover': 'rgba(255, 249, 232, 0.28)',
      '--image-overlay': 'rgba(0, 0, 0, 0.52)',
      '--app-bg-image':
        'linear-gradient(rgba(15,107,58,.055) 50%, transparent 50%), linear-gradient(90deg, rgba(15,107,58,.03) 1px, transparent 1px)',
      '--surface-bg-image':
        'linear-gradient(rgba(15,107,58,.04) 50%, transparent 50%)',
      '--card-bg-image': transparentLayer,
      '--bg-size': '100% 4px',
      '--surface-bg-size': '100% 4px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px var(--accent)',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
  },
  paper: {
    dark: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#22272e',
      '--bg-secondary': '#2a313a',
      '--bg-tertiary': '#38424e',
      '--bg-elevated': '#303b47',
      '--surface-glass': '#2a313a',
      '--surface-strong': '#303b47',
      '--accent': '#a3b6c4',
      '--accent-hover': '#c0cdd5',
      '--accent-soft': '#354453',
      '--accent-contrast': '#202c34',
      '--text-primary': '#f0f2f5',
      '--text-secondary': '#c9d0d9',
      '--text-muted': '#a5b1c0',
      '--card-bg': '#22272e',
      '--card-border': '#414c5b',
      '--border': '#414c5b',
      '--border-strong': '#748397',
      '--toolbar-bg': '#2a313a',
      '--panel-bg': '#2a313a',
      '--input-bg': '#22272e',
      '--input-border': '#414c5b',
      '--hover-bg': '#354150',
      '--active-bg': '#354453',
      '--scrollbar-thumb': '#687b92',
      '--shadow': '#00000020',
      '--shadow-strong': '#00000040',
      '--focus-ring': '#a3b6c4',
      '--radius-xs': '2px',
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-lg': '8px',
      '--radius-xl': '12px',
      '--radius-round': '20px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(14, 19, 26, 0.9)',
      '--overlay-control': 'rgba(228, 237, 247, 0.12)',
      '--overlay-control-hover': 'rgba(228, 237, 247, 0.24)',
      '--image-overlay': 'rgba(14, 19, 26, 0.52)',
      '--app-bg-image':
        'none',
      '--surface-bg-image':
        'none',
      '--card-bg-image':
        'none',
      '--bg-size': '22px 22px, auto',
      '--surface-bg-size': '18px 18px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'translateY(-2px)',
      '--card-hover-shadow': 'none',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
    light: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#f7f7f2',
      '--bg-secondary': '#ffffff',
      '--bg-tertiary': '#eaece6',
      '--bg-elevated': '#ffffff',
      '--surface-glass': '#ffffff',
      '--surface-strong': '#ffffff',
      '--accent': '#526f86',
      '--accent-hover': '#405b70',
      '--accent-soft': '#e8edf0',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#202522',
      '--text-secondary': '#515b55',
      '--text-muted': '#69736c',
      '--card-bg': '#f7f7f2',
      '--card-border': '#dfe3dc',
      '--border': '#dfe3dc',
      '--border-strong': '#aab4ac',
      '--toolbar-bg': '#ffffff',
      '--panel-bg': '#ffffff',
      '--input-bg': '#f1f3ef',
      '--input-border': '#dfe3dc',
      '--hover-bg': '#eef2ec',
      '--active-bg': '#e8edf0',
      '--scrollbar-thumb': '#b1bbb2',
      '--shadow': '#182c4010',
      '--shadow-strong': '#182c4020',
      '--focus-ring': '#526f86',
      '--radius-xs': '2px',
      '--radius-sm': '4px',
      '--radius-md': '6px',
      '--radius-lg': '8px',
      '--radius-xl': '12px',
      '--radius-round': '20px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(8, 6, 4, 0.88)',
      '--overlay-control': 'rgba(255, 249, 236, 0.14)',
      '--overlay-control-hover': 'rgba(255, 249, 236, 0.28)',
      '--image-overlay': 'rgba(8, 6, 4, 0.46)',
      '--app-bg-image':
        'none',
      '--surface-bg-image':
        'none',
      '--card-bg-image':
        'none',
      '--bg-size': '22px 22px, auto',
      '--surface-bg-size': '18px 18px',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'translateY(-2px)',
      '--card-hover-shadow': 'none',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
  },
  polaroid: {
    dark: {
      '--font-ui': '"Inter", system-ui, sans-serif',
      '--bg-primary': '#151210',
      '--bg-secondary': '#221d19',
      '--bg-tertiary': '#362b25',
      '--bg-elevated': '#2d251f',
      '--surface-glass': 'rgba(34, 29, 25, 0.86)',
      '--surface-strong': 'rgba(54, 43, 37, 0.94)',
      '--accent': '#f87171',
      '--accent-hover': '#93c5fd',
      '--accent-soft': 'rgba(248, 113, 113, 0.15)',
      '--accent-contrast': '#260b0b',
      '--text-primary': '#fff7ed',
      '--text-secondary': '#dec8af',
      '--text-muted': '#9d856d',
      '--card-bg': '#f8f1e3',
      '--card-border': 'rgba(255, 247, 237, 0.18)',
      '--border': 'rgba(255, 247, 237, 0.14)',
      '--border-strong': 'rgba(255, 247, 237, 0.24)',
      '--toolbar-bg': 'rgba(21, 18, 16, 0.84)',
      '--panel-bg': 'rgba(34, 29, 25, 0.96)',
      '--input-bg': 'rgba(255, 247, 237, 0.08)',
      '--input-border': 'rgba(255, 247, 237, 0.15)',
      '--hover-bg': 'rgba(255, 247, 237, 0.1)',
      '--active-bg': 'rgba(248, 113, 113, 0.15)',
      '--scrollbar-thumb': 'rgba(255, 247, 237, 0.2)',
      '--shadow': 'rgba(0, 0, 0, 0.28)',
      '--shadow-strong': 'rgba(0, 0, 0, 0.46)',
      '--focus-ring': 'rgba(248, 113, 113, 0.3)',
      '--radius-xs': '2px',
      '--radius-sm': '3px',
      '--radius-md': '4px',
      '--radius-lg': '5px',
      '--radius-xl': '6px',
      '--radius-round': '4px',
      '--hero-glow-1': 'rgba(248, 113, 113, 0.18)',
      '--hero-glow-2': 'rgba(147, 197, 253, 0.12)',
      '--overlay-bg': 'rgba(9, 6, 5, 0.9)',
      '--overlay-control': 'rgba(255, 247, 237, 0.13)',
      '--overlay-control-hover': 'rgba(255, 247, 237, 0.24)',
      '--image-overlay': 'rgba(9, 6, 5, 0.55)',
      '--app-bg-image':
        'radial-gradient(circle at 50% 12%, rgba(248,241,227,.08), transparent 34%)',
      '--surface-bg-image':
        'linear-gradient(135deg, rgba(248,241,227,.06), transparent)',
      '--card-bg-image': 'linear-gradient(#f8f1e3, #f8f1e3)',
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '9px 9px 24px',
      '--card-padding': '9px 9px 24px',
      '--card-hover-transform': 'translateY(-3px) rotate(-0.6deg)',
      '--card-hover-shadow': '0 22px 40px var(--shadow-strong)',
      '--selected-shadow':
        '0 0 0 2px var(--accent), 0 22px 40px var(--shadow-strong)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'blur(12px)',
      '--panel-backdrop-filter': 'blur(12px)',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
    light: {
      '--font-ui': '"Inter", system-ui, sans-serif',
      '--bg-primary': '#eadfcf',
      '--bg-secondary': '#fffaf2',
      '--bg-tertiary': '#dfd0bb',
      '--bg-elevated': '#ffffff',
      '--surface-glass': 'rgba(255, 250, 242, 0.88)',
      '--surface-strong': 'rgba(255, 255, 255, 0.96)',
      '--accent': '#d94f45',
      '--accent-hover': '#4f7fa8',
      '--accent-soft': 'rgba(217, 79, 69, 0.12)',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#31261c',
      '--text-secondary': '#6f5946',
      '--text-muted': '#a08a76',
      '--card-bg': '#fffaf2',
      '--card-border': 'rgba(49, 38, 28, 0.13)',
      '--border': 'rgba(49, 38, 28, 0.13)',
      '--border-strong': 'rgba(49, 38, 28, 0.23)',
      '--toolbar-bg': 'rgba(255, 250, 242, 0.9)',
      '--panel-bg': 'rgba(255, 250, 242, 0.97)',
      '--input-bg': 'rgba(49, 38, 28, 0.055)',
      '--input-border': 'rgba(49, 38, 28, 0.14)',
      '--hover-bg': 'rgba(49, 38, 28, 0.07)',
      '--active-bg': 'rgba(217, 79, 69, 0.12)',
      '--scrollbar-thumb': 'rgba(49, 38, 28, 0.22)',
      '--shadow': 'rgba(49, 38, 28, 0.16)',
      '--shadow-strong': 'rgba(49, 38, 28, 0.28)',
      '--focus-ring': 'rgba(217, 79, 69, 0.24)',
      '--radius-xs': '2px',
      '--radius-sm': '3px',
      '--radius-md': '4px',
      '--radius-lg': '5px',
      '--radius-xl': '6px',
      '--radius-round': '4px',
      '--hero-glow-1': 'rgba(217, 79, 69, 0.15)',
      '--hero-glow-2': 'rgba(79, 127, 168, 0.11)',
      '--overlay-bg': 'rgba(9, 6, 5, 0.88)',
      '--overlay-control': 'rgba(255, 250, 242, 0.14)',
      '--overlay-control-hover': 'rgba(255, 250, 242, 0.28)',
      '--image-overlay': 'rgba(9, 6, 5, 0.46)',
      '--app-bg-image':
        'radial-gradient(circle at 50% 10%, rgba(255,255,255,.44), transparent 34%)',
      '--surface-bg-image':
        'linear-gradient(135deg, rgba(255,255,255,.4), transparent)',
      '--card-bg-image': 'linear-gradient(#fffaf2, #fffaf2)',
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '9px 9px 24px',
      '--card-padding': '9px 9px 24px',
      '--card-hover-transform': 'translateY(-3px) rotate(-0.6deg)',
      '--card-hover-shadow': '0 22px 40px var(--shadow-strong)',
      '--selected-shadow':
        '0 0 0 2px var(--accent), 0 22px 40px var(--shadow-strong)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'blur(12px)',
      '--panel-backdrop-filter': 'blur(12px)',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
  },
  obsidian: {
    dark: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#0b0c10',
      '--bg-secondary': '#111218',
      '--bg-tertiary': '#24252f',
      '--bg-elevated': '#111218',
      '--surface-glass': '#0b0c10',
      '--surface-strong': '#111218',
      '--accent': '#c6bfd8',
      '--accent-hover': '#e5dff1',
      '--accent-soft': '#c6bfd81c',
      '--accent-contrast': '#0b0c10',
      '--text-primary': '#e4e0e9',
      '--text-secondary': '#b2adbd',
      '--text-muted': '#8f8a9c',
      '--card-bg': '#0b0c10',
      '--card-border': '#34333e',
      '--border': '#34333e',
      '--border-strong': '#e4e0e9',
      '--toolbar-bg': '#0b0c10',
      '--panel-bg': '#111218',
      '--input-bg': '#17181f',
      '--input-border': '#34333e',
      '--hover-bg': '#252630',
      '--active-bg': '#c6bfd826',
      '--scrollbar-thumb': '#e4e0e9',
      '--shadow': '#00000024',
      '--shadow-strong': '#00000050',
      '--focus-ring': '#c6bfd8',
      '--overlay-bg': '#08090df5',
      '--overlay-control': '#1a1b23',
      '--overlay-control-hover': '#363440',
      '--image-overlay': '#08090ddd',
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 8px 26px #00000038, inset 0 0 0 1px var(--accent)',
      '--selected-shadow': '0 0 0 3px var(--accent)',
      '--glow': 'none',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--app-bg-image': 'linear-gradient(120deg, transparent 55%, #8880aa06 55%, transparent 80%)',
      '--surface-bg-image': 'linear-gradient(135deg, #ffffff06, transparent 45%, #ffffff03)',
      '--card-bg-image': 'none',
    },
    light: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#dcd9e2',
      '--bg-secondary': '#e7e4ed',
      '--bg-tertiary': '#c9c5d2',
      '--bg-elevated': '#e7e4ed',
      '--surface-glass': '#dcd9e2',
      '--surface-strong': '#e7e4ed',
      '--accent': '#51435f',
      '--accent-hover': '#34283f',
      '--accent-soft': '#51435f14',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#24202c',
      '--text-secondary': '#5c5367',
      '--text-muted': '#72687d',
      '--card-bg': '#dcd9e2',
      '--card-border': '#ada5b8',
      '--border': '#ada5b8',
      '--border-strong': '#24202c',
      '--toolbar-bg': '#dcd9e2',
      '--panel-bg': '#e7e4ed',
      '--input-bg': '#eeebf2',
      '--input-border': '#ada5b8',
      '--hover-bg': '#d3ccdd',
      '--active-bg': '#51435f1a',
      '--scrollbar-thumb': '#24202c',
      '--shadow': '#00000024',
      '--shadow-strong': '#00000050',
      '--focus-ring': '#51435f',
      '--overlay-bg': '#08090df5',
      '--overlay-control': '#1a1b23',
      '--overlay-control-hover': '#363440',
      '--image-overlay': '#08090ddd',
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 8px 26px #00000038, inset 0 0 0 1px var(--accent)',
      '--selected-shadow': '0 0 0 3px var(--accent)',
      '--glow': 'none',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--app-bg-image': 'linear-gradient(120deg, transparent 55%, #8880aa06 55%, transparent 80%)',
      '--surface-bg-image': 'linear-gradient(135deg, #ffffff06, transparent 45%, #ffffff03)',
      '--card-bg-image': 'none',
    },
  },
  bauhaus: {
    dark: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#20211f',
      '--bg-secondary': '#282926',
      '--bg-tertiary': '#343530',
      '--bg-elevated': '#30312d',
      '--surface-glass': '#282926',
      '--surface-strong': '#30312d',
      '--accent': '#ed624e',
      '--accent-hover': '#f47c69',
      '--accent-soft': 'rgba(237, 98, 78, 0.14)',
      '--accent-contrast': '#20211f',
      '--text-primary': '#f2efdf',
      '--text-secondary': '#d1cfbf',
      '--text-muted': '#aaa99b',
      '--card-bg': '#282926',
      '--card-border': '#f2efdf',
      '--border': 'rgba(250, 250, 250, 0.28)',
      '--border-strong': '#f2efdf',
      '--toolbar-bg': '#20211f',
      '--panel-bg': '#282926',
      '--input-bg': 'rgba(250, 250, 250, 0.08)',
      '--input-border': 'rgba(250, 250, 250, 0.24)',
      '--hover-bg': 'rgba(250, 204, 21, 0.13)',
      '--active-bg': 'rgba(37, 99, 235, 0.18)',
      '--scrollbar-thumb': 'rgba(250, 204, 21, 0.45)',
      '--shadow': 'rgba(0, 0, 0, 0)',
      '--shadow-strong': 'rgba(0, 0, 0, 0)',
      '--focus-ring': 'rgba(250, 204, 21, 0.32)',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'rgba(225, 29, 72, 0)',
      '--hero-glow-2': 'rgba(250, 204, 21, 0)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.9)',
      '--overlay-control': 'rgba(250, 250, 250, 0.12)',
      '--overlay-control-hover': 'rgba(250, 204, 21, 0.24)',
      '--image-overlay': 'rgba(0, 0, 0, 0.56)',
      '--app-bg-image': transparentLayer,
      '--surface-bg-image': transparentLayer,
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 2px var(--text-primary)',
      '--selected-shadow': '0 0 0 3px var(--accent)',
      '--glow': 'none',
      '--shadow-clearance': '0px',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
    light: {
      '--font-ui': 'Arial, Helvetica, sans-serif',
      '--bg-primary': '#f1eedf',
      '--bg-secondary': '#e9e5d6',
      '--bg-tertiary': '#ded9c8',
      '--bg-elevated': '#ffffff',
      '--surface-glass': '#e9e5d6',
      '--surface-strong': '#f1eedf',
      '--accent': '#c63c2b',
      '--accent-hover': '#be3827',
      '--accent-soft': 'rgba(220, 38, 38, 0.12)',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#151515',
      '--text-secondary': '#44403c',
      '--text-muted': '#69675d',
      '--card-bg': '#f5f2e7',
      '--card-border': '#151515',
      '--border': 'rgba(21, 21, 21, 0.24)',
      '--border-strong': '#151515',
      '--toolbar-bg': '#f1eedf',
      '--panel-bg': '#f1eedf',
      '--input-bg': 'rgba(21, 21, 21, 0.045)',
      '--input-border': 'rgba(21, 21, 21, 0.22)',
      '--hover-bg': 'rgba(250, 204, 21, 0.18)',
      '--active-bg': 'rgba(37, 99, 235, 0.1)',
      '--scrollbar-thumb': 'rgba(21, 21, 21, 0.28)',
      '--shadow': 'rgba(0, 0, 0, 0)',
      '--shadow-strong': 'rgba(0, 0, 0, 0)',
      '--focus-ring': 'rgba(37, 99, 235, 0.22)',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'rgba(220, 38, 38, 0)',
      '--hero-glow-2': 'rgba(250, 204, 21, 0)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.88)',
      '--overlay-control': 'rgba(255, 250, 240, 0.14)',
      '--overlay-control-hover': 'rgba(250, 204, 21, 0.28)',
      '--image-overlay': 'rgba(0, 0, 0, 0.48)',
      '--app-bg-image': transparentLayer,
      '--surface-bg-image': transparentLayer,
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 2px var(--text-primary)',
      '--selected-shadow': '0 0 0 3px var(--accent)',
      '--glow': 'none',
      '--shadow-clearance': '0px',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'uppercase',
    },
  },
  glass: {
    dark: {
      '--font-ui': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      '--bg-primary': '#111111',
      '--bg-secondary': '#161616',
      '--bg-tertiary': '#202020',
      '--bg-elevated': '#1c1c1c',
      '--surface-glass': 'var(--liquid-fill)',
      '--surface-strong': 'var(--liquid-fill)',
      '--accent': '#f5f5f5',
      '--accent-hover': '#dddddd',
      '--accent-soft': 'rgba(175, 175, 175, 0.16)',
      '--accent-contrast': '#242424',
      '--text-primary': 'var(--liquid-ink)',
      '--text-secondary': 'var(--liquid-muted)',
      '--text-muted': 'var(--liquid-muted)',
      '--card-bg': 'transparent',
      '--card-border': '#ffffff66',
      '--border': '#ffffff22',
      '--border-strong': '#ffffffaa',
      '--toolbar-bg': 'rgba(17, 17, 17, 0.6)',
      '--panel-bg': 'var(--liquid-fill)',
      '--input-bg': '#ffffff0d',
      '--input-border': '#ffffff32',
      '--hover-bg': '#ffffff15',
      '--active-bg': '#d2d2d228',
      '--scrollbar-thumb': 'rgba(207, 207, 207, 0.26)',
      '--shadow': 'rgba(9, 9, 9, 0.38)',
      '--shadow-strong': 'rgba(9, 9, 9, 0.56)',
      '--focus-ring': 'rgba(175, 175, 175, 0.34)',
      '--radius-xs': '10px',
      '--radius-sm': '14px',
      '--radius-md': '18px',
      '--radius-lg': '26px',
      '--radius-xl': '36px',
      '--radius-round': '999px',
      '--hero-glow-1': 'rgba(175, 175, 175, 0.32)',
      '--hero-glow-2': 'rgba(113, 113, 113, 0.28)',
      '--overlay-bg': 'rgba(9, 9, 9, 0.9)',
      '--overlay-control': 'rgba(207, 207, 207, 0.14)',
      '--overlay-control-hover': 'rgba(175, 175, 175, 0.24)',
      '--image-overlay': 'rgba(9, 9, 9, 0.56)',
      '--app-bg-image':
        'radial-gradient(circle at 16% 18%, rgba(175, 175, 175,.26), transparent 38%), radial-gradient(circle at 84% 10%, rgba(113, 113, 113,.22), transparent 34%), linear-gradient(160deg, rgba(17, 17, 17,.4), transparent 48%)',
      '--surface-bg-image': 'none',
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px #ffffffaa',
      '--selected-shadow': '0 0 0 2px #fff, 0 0 0 5px var(--accent)',
      '--glow': 'none',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'blur(20px) saturate(1.25)',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
      '--glass-rim': 'rgba(207, 207, 207, 0.3)',
      '--glass-rim-strong': 'rgba(255, 255, 255, 0.48)',
      '--glass-specular':
        'linear-gradient(125deg, rgba(255, 255, 255,.4) 0%, rgba(255, 255, 255,.1) 30%, rgba(255, 255, 255,0) 52%)',
      '--glass-refraction-target':
        'linear-gradient(135deg, rgba(175, 175, 175,.3), rgba(113, 113, 113,.24) 52%, rgba(17, 17, 17,.22))',
      '--glass-chroma-cyan': 'rgba(175, 175, 175, 0.24)',
      '--glass-chroma-violet': 'rgba(113, 113, 113, 0.2)',
      '--glass-lens-shadow':
        'inset 0 1px 0 rgba(255, 255, 255,.34), inset 0 -1px 0 rgba(207, 207, 207,.12), 0 10px 28px rgba(175, 175, 175,.14), 0 2px 8px rgba(113, 113, 113,.12)',
    },
    light: {
      '--font-ui': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
      '--bg-primary': '#e9e9e9',
      '--bg-secondary': '#f6f6f6',
      '--bg-tertiary': '#dadada',
      '--bg-elevated': '#fcfcfc',
      '--surface-glass': 'var(--liquid-fill)',
      '--surface-strong': 'var(--liquid-fill)',
      '--accent': '#666666',
      '--accent-hover': '#515151',
      '--accent-soft': 'rgba(96, 96, 96, 0.14)',
      '--accent-contrast': '#fff',
      '--text-primary': 'var(--liquid-ink)',
      '--text-secondary': 'var(--liquid-muted)',
      '--text-muted': 'var(--liquid-muted)',
      '--card-bg': 'transparent',
      '--card-border': '#ffffff66',
      '--border': '#89898933',
      '--border-strong': '#ffffffaa',
      '--toolbar-bg': 'rgba(246, 246, 246, 0.8)',
      '--panel-bg': 'var(--liquid-fill)',
      '--input-bg': '#ffffff20',
      '--input-border': '#ffffff70',
      '--hover-bg': '#ffffff45',
      '--active-bg': '#dddddd52',
      '--scrollbar-thumb': 'rgba(118, 118, 118, 0.24)',
      '--shadow': 'rgba(24, 24, 24, 0.16)',
      '--shadow-strong': 'rgba(24, 24, 24, 0.26)',
      '--focus-ring': 'rgba(96, 96, 96, 0.3)',
      '--radius-xs': '10px',
      '--radius-sm': '14px',
      '--radius-md': '18px',
      '--radius-lg': '26px',
      '--radius-xl': '36px',
      '--radius-round': '999px',
      '--hero-glow-1': 'rgba(96, 96, 96, 0.3)',
      '--hero-glow-2': 'rgba(67, 67, 67, 0.24)',
      '--overlay-bg': 'rgba(17, 17, 17, 0.84)',
      '--overlay-control': 'rgba(255, 255, 255, 0.22)',
      '--overlay-control-hover': 'rgba(118, 118, 118, 0.24)',
      '--image-overlay': 'rgba(17, 17, 17, 0.44)',
      '--app-bg-image':
        'radial-gradient(circle at 18% 20%, rgba(96, 96, 96,.22), transparent 38%), radial-gradient(circle at 82% 8%, rgba(67, 67, 67,.16), transparent 34%), linear-gradient(160deg, rgba(255, 255, 255,.4), transparent 54%)',
      '--surface-bg-image': 'none',
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '0 0 0 1px #ffffffaa',
      '--selected-shadow': '0 0 0 2px #fff, 0 0 0 5px var(--accent)',
      '--glow': 'none',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'blur(20px) saturate(1.25)',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
      '--glass-rim': 'rgba(118, 118, 118, 0.26)',
      '--glass-rim-strong': 'rgba(255, 255, 255, 0.85)',
      '--glass-specular':
        'linear-gradient(125deg, rgba(255, 255, 255,.9) 0%, rgba(255, 255, 255,.4) 24%, rgba(255, 255, 255,0) 52%)',
      '--glass-refraction-target':
        'linear-gradient(135deg, rgba(118, 118, 118,.2), rgba(85, 85, 85,.16) 52%, rgba(255, 255, 255,.32))',
      '--glass-chroma-cyan': 'rgba(118, 118, 118, 0.18)',
      '--glass-chroma-violet': 'rgba(85, 85, 85, 0.14)',
      '--glass-lens-shadow':
        'inset 0 1px 0 rgba(255, 255, 255,.75), inset 0 -1px 0 rgba(118, 118, 118,.2), 0 10px 26px rgba(118, 118, 118,.14), 0 2px 8px rgba(85, 85, 85,.1)',
    },
  },
  minimal: {
    dark: {
      '--font-ui': '"Helvetica Neue", Helvetica, Arial, sans-serif',
      '--bg-primary': '#111111',
      '--bg-secondary': '#111111',
      '--bg-tertiary': '#1b1b1b',
      '--bg-elevated': '#141414',
      '--surface-glass': 'rgba(16, 16, 16, 0.9)',
      '--surface-strong': 'rgba(27, 27, 27, 0.96)',
      '--accent': '#d4d4d4',
      '--accent-hover': '#ffffff',
      '--accent-soft': 'rgba(212, 212, 212, 0.12)',
      '--accent-contrast': '#111111',
      '--text-primary': '#f5f5f5',
      '--text-secondary': '#bdbdbd',
      '--text-muted': '#999999',
      '--card-bg': 'transparent',
      '--card-border': 'transparent',
      '--border': 'rgba(255, 255, 255, 0.1)',
      '--border-strong': 'rgba(255, 255, 255, 0.2)',
      '--toolbar-bg': 'rgba(5, 5, 5, 0.92)',
      '--panel-bg': 'rgba(16, 16, 16, 0.96)',
      '--input-bg': 'transparent',
      '--input-border': 'rgba(255, 255, 255, 0.13)',
      '--hover-bg': 'rgba(255, 255, 255, 0.08)',
      '--active-bg': 'rgba(255, 255, 255, 0.13)',
      '--scrollbar-thumb': 'rgba(255, 255, 255, 0.18)',
      '--shadow': 'transparent',
      '--shadow-strong': 'transparent',
      '--focus-ring': '#ffffff',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(0, 0, 0, 0.94)',
      '--overlay-control': 'rgba(255, 255, 255, 0.1)',
      '--overlay-control-hover': 'rgba(255, 255, 255, 0.2)',
      '--image-overlay': 'rgba(0, 0, 0, 0.58)',
      '--app-bg-image': transparentLayer,
      '--surface-bg-image': transparentLayer,
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': 'none',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
    light: {
      '--font-ui': '"Helvetica Neue", Helvetica, Arial, sans-serif',
      '--bg-primary': '#ffffff',
      '--bg-secondary': '#ffffff',
      '--bg-tertiary': '#eeeeee',
      '--bg-elevated': '#ffffff',
      '--surface-glass': 'rgba(255, 255, 255, 0.9)',
      '--surface-strong': 'rgba(255, 255, 255, 0.98)',
      '--accent': '#111111',
      '--accent-hover': '#444444',
      '--accent-soft': 'rgba(17, 17, 17, 0.08)',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#111111',
      '--text-secondary': '#555555',
      '--text-muted': '#707070',
      '--card-bg': '#ffffff',
      '--card-border': 'transparent',
      '--border': 'rgba(17, 17, 17, 0.1)',
      '--border-strong': 'rgba(17, 17, 17, 0.2)',
      '--toolbar-bg': '#ffffff',
      '--panel-bg': 'rgba(255, 255, 255, 0.98)',
      '--input-bg': 'transparent',
      '--input-border': 'rgba(17, 17, 17, 0.12)',
      '--hover-bg': 'rgba(17, 17, 17, 0.06)',
      '--active-bg': 'rgba(17, 17, 17, 0.08)',
      '--scrollbar-thumb': 'rgba(17, 17, 17, 0.18)',
      '--shadow': 'transparent',
      '--shadow-strong': 'transparent',
      '--focus-ring': '#111111',
      '--radius-xs': '0px',
      '--radius-sm': '0px',
      '--radius-md': '0px',
      '--radius-lg': '0px',
      '--radius-xl': '0px',
      '--radius-round': '0px',
      '--hero-glow-1': 'transparent',
      '--hero-glow-2': 'transparent',
      '--overlay-bg': 'rgba(0, 0, 0, 0.9)',
      '--overlay-control': 'rgba(255, 255, 255, 0.14)',
      '--overlay-control-hover': 'rgba(255, 255, 255, 0.28)',
      '--image-overlay': 'rgba(0, 0, 0, 0.48)',
      '--app-bg-image': transparentLayer,
      '--surface-bg-image': transparentLayer,
      '--card-bg-image': transparentLayer,
      '--bg-size': 'auto',
      '--surface-bg-size': 'auto',
      '--border-width': '1px',
      '--border-style': 'solid',
      '--control-border-style': 'solid',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': 'none',
      '--selected-shadow': '0 0 0 2px var(--accent)',
      '--glow': '0 0 0 transparent',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
  },
  retroOs: {
    dark: {
      '--font-ui': 'Tahoma, "MS Sans Serif", system-ui, sans-serif',
      '--bg-primary': '#202033',
      '--bg-secondary': '#2b2b3f',
      '--bg-tertiary': '#3a3a52',
      '--bg-elevated': '#33334a',
      '--surface-glass': 'rgba(43, 43, 63, 0.96)',
      '--surface-strong': 'rgba(58, 58, 82, 0.98)',
      '--accent': '#60a5fa',
      '--accent-hover': '#93c5fd',
      '--accent-soft': 'rgba(96, 165, 250, 0.14)',
      '--accent-contrast': '#07172a',
      '--text-primary': '#f4f4f5',
      '--text-secondary': '#d4d4d8',
      '--text-muted': '#a1a1aa',
      '--card-bg': 'rgba(63, 63, 86, 0.82)',
      '--card-border': 'rgba(244, 244, 245, 0.22)',
      '--border': 'rgba(244, 244, 245, 0.18)',
      '--border-strong': 'rgba(244, 244, 245, 0.34)',
      '--toolbar-bg': 'rgba(32, 32, 51, 0.98)',
      '--panel-bg': 'rgba(43, 43, 63, 0.98)',
      '--input-bg': 'rgba(0, 0, 0, 0.16)',
      '--input-border': 'rgba(244, 244, 245, 0.28)',
      '--hover-bg': 'rgba(96, 165, 250, 0.14)',
      '--active-bg': 'rgba(96, 165, 250, 0.2)',
      '--scrollbar-thumb': 'rgba(244, 244, 245, 0.24)',
      '--shadow': 'rgba(0, 0, 0, 0.32)',
      '--shadow-strong': 'rgba(0, 0, 0, 0.5)',
      '--focus-ring': 'rgba(96, 165, 250, 0.26)',
      '--radius-xs': '0px',
      '--radius-sm': '1px',
      '--radius-md': '2px',
      '--radius-lg': '3px',
      '--radius-xl': '3px',
      '--radius-round': '2px',
      '--hero-glow-1': 'rgba(96, 165, 250, 0.18)',
      '--hero-glow-2': 'rgba(244, 244, 245, 0.08)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.9)',
      '--overlay-control': 'rgba(244, 244, 245, 0.12)',
      '--overlay-control-hover': 'rgba(96, 165, 250, 0.22)',
      '--image-overlay': 'rgba(0, 0, 0, 0.56)',
      '--app-bg-image':
        'linear-gradient(45deg, rgba(255,255,255,.025) 25%, transparent 25%), linear-gradient(-45deg, rgba(255,255,255,.025) 25%, transparent 25%)',
      '--surface-bg-image':
        'linear-gradient(rgba(255,255,255,.08), transparent 1px)',
      '--card-bg-image': transparentLayer,
      '--bg-size': '18px 18px',
      '--surface-bg-size': '100% 3px',
      '--border-width': '2px',
      '--border-style': 'outset',
      '--control-border-style': 'outset',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '3px 3px 0 var(--shadow)',
      '--selected-shadow':
        '0 0 0 2px var(--accent), inset 2px 2px 0 rgba(255,255,255,.18)',
      '--glow': '3px 3px 0 var(--shadow)',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
    light: {
      '--font-ui': 'Tahoma, "MS Sans Serif", system-ui, sans-serif',
      '--bg-primary': '#bfc2c7',
      '--bg-secondary': '#d9d9d9',
      '--bg-tertiary': '#c7c7c7',
      '--bg-elevated': '#eeeeee',
      '--surface-glass': 'rgba(217, 217, 217, 0.98)',
      '--surface-strong': 'rgba(238, 238, 238, 0.98)',
      '--accent': '#2563eb',
      '--accent-hover': '#1d4ed8',
      '--accent-soft': 'rgba(37, 99, 235, 0.12)',
      '--accent-contrast': '#ffffff',
      '--text-primary': '#111111',
      '--text-secondary': '#3f3f46',
      '--text-muted': '#71717a',
      '--card-bg': '#eeeeee',
      '--card-border': '#8a8a8a',
      '--border': '#8a8a8a',
      '--border-strong': '#3f3f46',
      '--toolbar-bg': '#d9d9d9',
      '--panel-bg': '#d9d9d9',
      '--input-bg': '#ffffff',
      '--input-border': '#8a8a8a',
      '--hover-bg': 'rgba(37, 99, 235, 0.1)',
      '--active-bg': 'rgba(37, 99, 235, 0.16)',
      '--scrollbar-thumb': 'rgba(17, 17, 17, 0.3)',
      '--shadow': 'rgba(17, 17, 17, 0.16)',
      '--shadow-strong': 'rgba(17, 17, 17, 0.28)',
      '--focus-ring': 'rgba(37, 99, 235, 0.22)',
      '--radius-xs': '0px',
      '--radius-sm': '1px',
      '--radius-md': '2px',
      '--radius-lg': '3px',
      '--radius-xl': '3px',
      '--radius-round': '2px',
      '--hero-glow-1': 'rgba(37, 99, 235, 0.12)',
      '--hero-glow-2': 'rgba(17, 17, 17, 0.06)',
      '--overlay-bg': 'rgba(0, 0, 0, 0.88)',
      '--overlay-control': 'rgba(255, 255, 255, 0.14)',
      '--overlay-control-hover': 'rgba(37, 99, 235, 0.26)',
      '--image-overlay': 'rgba(0, 0, 0, 0.48)',
      '--app-bg-image':
        'linear-gradient(45deg, rgba(255,255,255,.18) 25%, transparent 25%), linear-gradient(-45deg, rgba(0,0,0,.035) 25%, transparent 25%)',
      '--surface-bg-image':
        'linear-gradient(rgba(255,255,255,.24), transparent 1px)',
      '--card-bg-image': transparentLayer,
      '--bg-size': '18px 18px',
      '--surface-bg-size': '100% 3px',
      '--border-width': '2px',
      '--border-style': 'outset',
      '--control-border-style': 'outset',
      '--card-frame-width': '0px',
      '--card-padding': '0px',
      '--card-hover-transform': 'none',
      '--card-hover-shadow': '3px 3px 0 var(--shadow)',
      '--selected-shadow':
        '0 0 0 2px var(--accent), inset 2px 2px 0 rgba(255,255,255,.44)',
      '--glow': '3px 3px 0 var(--shadow)',
      '--toolbar-backdrop-filter': 'none',
      '--panel-backdrop-filter': 'none',
      '--surface-clip-path': 'none',
      '--control-transform': 'none',
    },
  },
} satisfies Record<ThemePack, ThemeDefinition>

const getThemeDefinition = (pack: ThemePack): ThemeDefinition => {
  switch (pack) {
    case 'blueprint':
      return THEMES.blueprint
    case 'terminal':
      return THEMES.terminal
    case 'paper':
      return THEMES.paper
    case 'polaroid':
      return THEMES.polaroid
    case 'obsidian':
      return THEMES.obsidian
    case 'bauhaus':
      return THEMES.bauhaus
    case 'glass':
      return THEMES.glass
    case 'minimal':
      return THEMES.minimal
    case 'retroOs':
      return THEMES.retroOs
    default:
      return THEMES.paper
  }
}

export const activeThemeVariables = computed(
  () => getThemeDefinition(themePack())[resolvedThemeMode()],
  'theme.activeVariables',
)

export const GlobalStyles = () => {
  return (
    <div
      css={`
        :root {
          font-family: var(--font-ui);
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

        *,
        *::before,
        *::after {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }

        body {
          background: var(--bg-primary);
          background-image: var(--app-bg-image);
          background-size: var(--bg-size);
          color: var(--text-primary);
          transition:
            background 0.3s,
            color 0.3s;
          min-height: 100vh;
          overflow-x: hidden;
        }

        ::selection {
          background: var(--accent-soft);
          color: var(--text-primary);
        }

        a {
          color: var(--accent);
          text-decoration: none;
        }

        button {
          cursor: pointer;
          font-family: inherit;
          font-size: inherit;
        }

        input,
        select,
        textarea {
          font-family: inherit;
          font-size: inherit;
        }

        button,
        input,
        select,
        textarea {
          outline: none;
        }

        button:focus-visible,
        input:focus-visible,
        select:focus-visible,
        textarea:focus-visible {
          box-shadow: 0 0 0 3px var(--focus-ring);
        }

        ::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }

        ::-webkit-scrollbar-track {
          background: transparent;
        }

        ::-webkit-scrollbar-thumb {
          background: var(--scrollbar-thumb);
          border-radius: var(--radius-round);
        }

        ::-webkit-scrollbar-thumb:hover {
          background: var(--accent);
        }
      `}
      style={{ display: 'none' }}
    />
  )
}
