name: Lint markdown

on:
  pull_request:
    types: [opened, synchronize, reopened,  ready_for_review]
    paths:
      - "**.md"
      - "**.mdx"

jobs:
  remark-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.2"

      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        with:
          cache: true

      - run: pnpm install --ignore-scripts

      - run: node --run lint:md
