name: Preview

on:
  push:
    branches:
      - v1001
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  publish-preview:
    needs: test
    uses: ./.github/workflows/publish-preview.yml
