name: Test

on: workflow_call

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: '24.2'

      - name: Setup pnpm
        uses: pnpm/action-setup@1e1c8eafbd745f64b1ef30a7d7ed7965034c486c
        with:
          cache: true

      - name: Install dependencies
        run: |
          pnpm install --ignore-scripts
          pnpx playwright install --with-deps chromium

      - name: Run tests
        run: pnpm test

      - name: Upload admin ui artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: admin-ui-artifacts
          if-no-files-found: ignore
          path: |
            packages/admin/**/__screenshots__/**
            packages/admin/**/.vitest/**
            packages/admin/**/test-results/**
